---
# copyright Utrecht University
# This playbook provisions a Matomo server instance with the Zabbix agent

- name: Local checks
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Verify Ansible version meets requirements
      ansible.builtin.assert:
        that: "ansible_version.full is version('2.9', '>=')"
        msg: >
          "You must update Ansible to at least 2.9 to deploy Matomo using Ansible."


- name: Provision Zabbix agent
  hosts: all
  become: true
  roles:
    - zabbix_agent
